# --- CONFIGURACIÓN PRINCIPAL DE LA APP ---
client_id = "c107b3c66a61fb6227c2a94ebee29609"
name = "modo"
application_url = "https://gardenlife-modo.vercel.app"
embedded = true

# --- WEBHOOKS ---
[webhooks]
api_version = "2025-07"

# --- PERMISOS DE ACCESO ---
[access_scopes]
scopes = "write_products"
optional_scopes = []
use_legacy_install_flow = false

# --- AUTENTICACIÓN ---
[auth]
redirect_urls = [
  "https://gardenlife-modo.vercel.app/auth/callback",
  "https://gardenlife-modo.vercel.app/auth/shopify/callback",
  "https://gardenlife-modo.vercel.app/api/auth/callback"
]

# --- APP PROXY ---
[app_proxy]
url = "https://gardenlife-modo.vercel.app"
subpath = "modo"
prefix = "apps"

# --- EXTENSIÓN DE CHECKOUT (MODO) ---
[[extensions]]
type = "checkout_ui_extension"
path = "extensions/modo-pay"

