# shopify.app.toml

client_id = "44d5b4da30178eb0a61c04c874a79f64"
name = "gardenlife_modo"

# ✅ PRODUCCIÓN: tu app hosteada en Vercel
application_url = "https://gardenlife-modo.vercel.app"
embedded = true
handle = "gardenlife_modo"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
scopes = "write_products"

[auth]
# ✅ Callbacks derivados de application_url
redirect_urls = [
  "https://gardenlife-modo.vercel.app/auth/callback",
  "https://gardenlife-modo.vercel.app/auth/shopify/callback",
  "https://gardenlife-modo.vercel.app/api/auth/callback"
]

[pos]
embedded = false

# ✅ APP PROXY: esto habilita /apps/modo/... en tu tienda
[app_proxy]
# Dónde Shopify debe reenviar las requests del proxy
url = "https://gardenlife-modo.vercel.app"
# Ruta pública en la tienda: /apps/<prefix>/<subpath>/...
prefix = "apps"
subpath = "modo"
