# shopify.app.toml

client_id = "653a5253a7ef9c0ac99a7cb24e024c99"
name = "modo"
handle = "modo"

application_url = "https://gardenlife-modo.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# incluimos write_app_proxy
scopes = "read_draft_orders,write_draft_orders,read_customers,read_orders,write_orders,write_app_proxy"

[auth]
redirect_urls = [
  "https://gardenlife-modo.vercel.app/auth/callback",
  "https://gardenlife-modo.vercel.app/auth/shopify/callback",
  "https://gardenlife-modo.vercel.app/api/auth/callback"
]

[pos]
embedded = false

# App Proxy sin /api
[app_proxy]
url    = "https://gardenlife-modo.vercel.app"
prefix = "apps"
subpath = "modo"
