# shopify.app.toml

client_id = "44d5b4da30178eb0a61c04c874a79f64"
name = "gardenlife_modo"

# ✅ PRODUCCIÓN: tu app hosteada en Vercel
application_url = "https://gardenlife-modo.vercel.app"
embedded = true
handle = "gardenlife_modo"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
scopes = "read_draft_orders,write_draft_orders,read_customers,read_orders,write_orders"

[auth]
# ✅ Callbacks derivados de application_url
redirect_urls = [
  "https://gardenlife-modo.vercel.app/auth/callback",
  "https://gardenlife-modo.vercel.app/auth/shopify/callback",
  "https://gardenlife-modo.vercel.app/api/auth/callback"
]

[pos]
embedded = false

# ✅ APP PROXY: esto habilita /apps/modo/... en tu tienda
[app_proxy]
url = "https://gardenlife-modo.vercel.app/api"  # ← AGREGAR /api
prefix = "apps"
subpath = "modo"

