name: MODO y Apps Bancarias
type: checkout_ui_extension
api_version: 2025-07
targets:
  - target: purchase.checkout.block.render
    module: ./src/index.jsx
# (sin default_placement)
capabilities:
  network_access: true

