name: MODO y Apps Bancarias (v27)
type: checkout_ui_extension
api_version: 2025-07
extension_points:
  - purchase.checkout.block.render
entry: src/index.jsx
capabilities:
  network_access: true
  api_access: true

