name: MODO Pay Block
type: checkout_ui_extension
api_version: 2024-10

extension_points:
  - purchase.checkout.block.render

entry: src/index.jsx

capabilities:
  network_access: true
  api_access: true
