api_version = "2024-07"

[[extensions]]
name = "MODO y Apps Bancarias"
handle = "modo-pay-block"
type = "ui_extension"
description = "Pago con MODO: abre QR/deeplink en el checkout."

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/index.jsx"
default_placement = "WALLETS1"
